### PR TITLE
Extra jammy

### PR DESCRIPTION
**Pull request by wash2**
based on https://www.figma.com/file/yFxlLCtVYLHMuHBNSXLf7O/Icon-theme?node-id=302%3A3563&mode=dev

### CODE REVIEW

**Comment by wash2** [comment]
I'm not sure about some of the remaining extra icons, including the network status icons, but I think this is pretty ready for review.

**Comment by wash2** [comment]
It seems like we will be adding more network icons for secure wifi connections of the various strengths

**Comment by wash2** [comment]
I guess this can just be reviewed as is and we can add more network icons later.

**Comment by wash2** [comment]
Maybe I could move the older icons into a legacy folder? And all of the new icons for cosmic could be in extra.

**Comment by maria-komarova** [comment]
What legacy icons?

**Pull request merged**
